######################################################################
# Automatically generated by qmake (2.01a) niedz. sty 11 20:09:26 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += initdb.hpp mainwindow.hpp
SOURCES += main.cpp mainwindow.cpp initdb.cpp
